version: '3'

services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:15.2-bullseye
    restart: always
    environment:
      TZ: "Asia/Seoul"
      # psql -h localhost -U mark chat_db
      POSTGRES_DB: chat_db
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
#    volumes:
#      - ./postgres/data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      pg_network:
        ipv4_address: 172.30.0.2
  pgadmin:
    container_name: pgadmin
    image: docker.io/dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@markruler.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      pg_network:
        ipv4_address: 172.30.0.3
    depends_on:
      - postgres

networks:
  pg_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
